"""empty message

Revision ID: 194cfc6adfdb
Revises: 55c3098fa940
Create Date: 2019-03-02 19:24:09.810009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194cfc6adfdb'
down_revision = '55c3098fa940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
